name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install fastapi uvicorn opencv-python-headless prometheus-client ultralytics python-multipart

    - name: Run basic test
      run: |
        python -c "print('Pipeline working successfully')"

    - name: Build Docker Image
      run: |
        docker build -t mlops-project .
